### ISSUE TITLE
Loss functions - problem with quantifier compilation (comparison between 'function' and 'float')

### ISSUE THREAD

**Issue by ndslusarz** [vehicle-lang/vehicle#403] opened 2023-02-01 19:52 UTC
When trying to run the python script for the modified mnist example (both can be found on `loss_experiments `branch in `vehicle-python/tests` as `mnist.vcl` and `test_mnist.py`) it returnes an error:

```
File "e:\vehicle\vehicle\vehicle-python\tests\__init__.py", line 325, in result_func        
    max_loss = max(max_loss, body_loss(context))
TypeError: '>' not supported between instances of 'function' and 'float'
```

This errors out inside the compilation of a forall quantifier. Speicifcally it seems that `body_loss(context)` which is supposed to compile the value of everything inside the forall, does not actually compile to a number and is still a function. As in specification a helper function is called immeditaely after forall I suspect there is something wrong in how the translation handles translating these, probably linked to the latest fix which makes the property compile first. I might be wrong as I haven't been able to fix it yet.

**Comment by MatthewDaggitt** [comment] 2023-02-02 03:11
Can't reproduce as the Vehicle compiler itself doesn't compile on `loss_experiments` branch.  In particular I think the problem is this commit: https://github.com/vehicle-lang/vehicle/commit/adcb423214099a98e3ece1dc0f5ee94765e6a3b3 where the merge has gone wrong.

**Comment by ndslusarz** [comment] 2023-02-02 07:24
I think I fixed the thing causing the problem with compiler (compiles locally at least). Let me know if not.

**Comment by MatthewDaggitt** [comment] 2023-02-03 03:32
Fixed by https://github.com/vehicle-lang/vehicle/pull/406

**Closed as completed** 2023-02-03 05:55 UTC
Labels: compiler:loss-backend, bindings:python
